import { Inter } from "next/font/google";
import "./globals.css";
import Banner from "./ui/Banner";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
    appearance={{
      elements: {
        formButtonPrimary:
          "bg-teal-500 hover:bg-teal-400 text-sm normal-case",
      },
    }}
    >
      <html lang="en">
        <body
          className={`${inter.className} flex flex-col justify-start items-center gap-8 mt-4`}
        >
          <Banner />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
